name: flutter_template
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  pin_code_fields: ^7.4.0
  http: ^1.1.0
  flutter_riverpod: ^2.3.6
  intl: ^0.18.0
  cached_network_image: ^3.2.3
  shared_preferences:
  webview_flutter: ^4.2.0
  file_picker: ^5.3.0
  fluttertoast: ^8.2.2
  infinite_scroll_pagination: ^3.2.0
  responsive_framework: ^1.0.0
  url_launcher: ^6.1.11
  go_router: ^7.0.1
  firebase_core: ^2.13.0
  firebase_messaging: ^14.6.1
  flutter_local_notifications:
  device_info_plus:
  flutter_svg:
  image_picker:
  json_annotation: ^4.8.1
  firebase_analytics: ^10.4.1
  share_plus: ^7.0.0
  faker:
  flutter_screenutil: ^5.8.4
  carousel_slider: ^4.2.1
  photo_view: ^0.14.0
  video_player: ^2.7.0
  flutter_cache_manager: ^3.3.1
  percent_indicator: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.4.4
  flutter_gen_runner:
  json_serializable: ^6.7.0
  intl_translation: ^0.18.2
  change_app_package_name: ^1.1.0

flutter:

  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/iconly/bold/
    - assets/iconly/broken/
    - assets/iconly/bulk/
    - assets/iconly/curved/
    - assets/iconly/light/
    - assets/iconly/light-outline/
    - assets/iconly/two-tone/

  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-Light.ttf
          weight: 300
        - asset: assets/fonts/Urbanist-Regular.ttf
          weight: 400
        - asset: assets/fonts/Urbanist-Medium.ttf
          weight: 500
        - asset: assets/fonts/Urbanist-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Urbanist-Bold.ttf
          weight: 700
flutter_gen:
  output: lib/core/util/gen/
flutter_intl:

  enabled: true
  class_name: S
  main_locale: en
  arb_dir: lib/core/util/l10n
  output_dir: lib/core/util/gen
  use_deferred_loading: false


